# Generated by Django 4.2.4 on 2023-09-21 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_tag_articles_scope"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scope",
            old_name="article",
            new_name="articles",
        ),
        migrations.RenameField(
            model_name="scope",
            old_name="tag",
            new_name="tags",
        ),
    ]
