# Generated by Django 4.2.4 on 2023-09-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_rename_article_scope_articles_rename_tag_scope_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleScope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Основной"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="tag",
            name="articles",
        ),
        migrations.AddField(
            model_name="article",
            name="tag",
            field=models.ManyToManyField(related_name="tag", to="articles.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Тег"),
        ),
        migrations.DeleteModel(
            name="Scope",
        ),
        migrations.AddField(
            model_name="articlescope",
            name="articles",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="articlescope",
            name="tags",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.tag",
            ),
        ),
    ]
