# Generated by Django 4.2.4 on 2023-09-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_articlescope_remove_tag_articles_article_tag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlescope",
            old_name="articles",
            new_name="article",
        ),
        migrations.RenameField(
            model_name="articlescope",
            old_name="tags",
            new_name="tag",
        ),
        migrations.RemoveField(
            model_name="article",
            name="tag",
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="tag",
                through="articles.ArticleScope",
                to="articles.tag",
                verbose_name="Тематики статьи",
            ),
        ),
    ]
