# Generated by Django 4.2.4 on 2023-09-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_rename_articles_articlescope_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlescope",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.article",
                verbose_name="Статья",
            ),
        ),
        migrations.AlterField(
            model_name="articlescope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.tag",
                verbose_name="Тэг",
            ),
        ),
    ]
