# Generated by Django 4.2.4 on 2023-09-23 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0007_alter_articlescope_article_alter_articlescope_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlescope",
            options={"verbose_name": "Че та", "verbose_name_plural": "Че та 1"},
        ),
    ]
