# Generated by Django 4.2.4 on 2023-09-23 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0009_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlescope",
            options={
                "verbose_name": "Привязка",
                "verbose_name_plural": "В списке тэгов",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
        migrations.RenameField(
            model_name="article",
            old_name="tags",
            new_name="tag",
        ),
        migrations.RenameField(
            model_name="articlescope",
            old_name="article",
            new_name="articles",
        ),
        migrations.RenameField(
            model_name="articlescope",
            old_name="tag",
            new_name="tags",
        ),
    ]
