# Generated by Django 4.2.4 on 2023-09-23 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0010_alter_articlescope_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="tag",
            new_name="tags",
        ),
        migrations.RenameField(
            model_name="articlescope",
            old_name="articles",
            new_name="article",
        ),
        migrations.RenameField(
            model_name="articlescope",
            old_name="tags",
            new_name="tag",
        ),
    ]
