# Generated by Django 4.2.4 on 2023-09-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0011_rename_tag_article_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="articlescope",
            options={
                "verbose_name": "Привязка",
                "verbose_name_plural": "Тематики статьи",
            },
        ),
        migrations.AlterField(
            model_name="articlescope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.tag",
                verbose_name="Раздел",
            ),
        ),
    ]
