# Generated by Django 4.2.4 on 2023-09-24 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0012_alter_article_options_alter_articlescope_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
    ]
