# Generated by Django 4.2.4 on 2023-09-24 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0014_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
    ]
